-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 09:45:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gearBoss
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gearBoss` ;

-- -----------------------------------------------------
-- Schema gearBoss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gearBoss` ;
USE `gearBoss` ;

-- -----------------------------------------------------
-- Table `gearBoss`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`user` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`userID`));


-- -----------------------------------------------------
-- Table `gearBoss`.`gearCondition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`gearCondition` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`gearCondition` (
  `gearConditionID` INT NOT NULL AUTO_INCREMENT,
  `conditionDescription` VARCHAR(45) NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`gearConditionID`),
  INDEX `fk_gearCondition_3_idx` (`updatedBy` ASC) VISIBLE,
  CONSTRAINT `fk_gearCondition_2`
    FOREIGN KEY (`createdBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gearCondition_3`
    FOREIGN KEY (`updatedBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`gearType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`gearType` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`gearType` (
  `gearTypeID` INT NOT NULL AUTO_INCREMENT,
  `gearTypeDescription` VARCHAR(45) NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`gearTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`gearStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`gearStatus` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`gearStatus` (
  `gearStatusID` INT NOT NULL AUTO_INCREMENT,
  `gearStatusDescription` VARCHAR(45) NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`gearStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`gear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`gear` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`gear` (
  `gearID` INT NOT NULL AUTO_INCREMENT,
  `gearName` VARCHAR(45) NULL,
  `gearTypeID` INT NULL,
  `gearConditionID` INT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `gearStatusID` INT NULL,
  `gearLabel` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NULL,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`gearID`),
  INDEX `gearCondition_idx` (`gearConditionID` ASC) VISIBLE,
  INDEX `gearType_idx` (`gearTypeID` ASC) VISIBLE,
  INDEX `fk_gear_1_idx` (`gearStatusID` ASC) VISIBLE,
  INDEX `fk_gear_2_idx` (`createdBy` ASC) VISIBLE,
  INDEX `fk_gear_3_idx` (`updatedBy` ASC) VISIBLE,
  CONSTRAINT `gearCondition`
    FOREIGN KEY (`gearConditionID`)
    REFERENCES `gearBoss`.`gearCondition` (`gearConditionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gearType`
    FOREIGN KEY (`gearTypeID`)
    REFERENCES `gearBoss`.`gearType` (`gearTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gear_1`
    FOREIGN KEY (`gearStatusID`)
    REFERENCES `gearBoss`.`gearStatus` (`gearStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gear_2`
    FOREIGN KEY (`createdBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gear_3`
    FOREIGN KEY (`updatedBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`description` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`description` (
  `descriptionID` INT NOT NULL AUTO_INCREMENT,
  `gearID` INT NULL,
  `description` BLOB NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`descriptionID`),
  INDEX `fk_description_1_idx` (`gearID` ASC) VISIBLE,
  INDEX `fk_description_2_idx` (`createdBy` ASC) VISIBLE,
  INDEX `fk_description_3_idx` (`updatedBy` ASC) VISIBLE,
  CONSTRAINT `fk_description_1`
    FOREIGN KEY (`gearID`)
    REFERENCES `gearBoss`.`gear` (`gearID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_description_2`
    FOREIGN KEY (`createdBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_description_3`
    FOREIGN KEY (`updatedBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`photos` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`photos` (
  `photosID` INT NOT NULL AUTO_INCREMENT,
  `photoURL` VARCHAR(45) NULL,
  `gearID` INT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`photosID`),
  INDEX `fk_photos_1_idx` (`gearID` ASC) VISIBLE,
  CONSTRAINT `fk_photos_1`
    FOREIGN KEY (`gearID`)
    REFERENCES `gearBoss`.`gear` (`gearID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`skater`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`skater` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`skater` (
  `skaterID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `contacted` TINYINT NULL,
  `position` VARCHAR(45) NULL,
  `referredBy` INT NULL,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`skaterID`),
  INDEX `fk_skater_1_idx` (`referredBy` ASC) VISIBLE,
  INDEX `fk_skater_2_idx` (`createdBy` ASC) VISIBLE,
  INDEX `fk_skater_3_idx` (`updatedBy` ASC) VISIBLE,
  CONSTRAINT `fk_skater_1`
    FOREIGN KEY (`referredBy`)
    REFERENCES `gearBoss`.`skater` (`skaterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skater_2`
    FOREIGN KEY (`createdBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skater_3`
    FOREIGN KEY (`updatedBy`)
    REFERENCES `gearBoss`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`gearSkater`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`gearSkater` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`gearSkater` (
  `gearSkaterID` INT NOT NULL AUTO_INCREMENT,
  `gearID` INT NULL,
  `skaterID` INT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `activeInd` TINYINT NULL,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`gearSkaterID`),
  INDEX `fk_gearSkater_1_idx` (`gearID` ASC) VISIBLE,
  INDEX `fk_gearSkater_2_idx` (`skaterID` ASC) VISIBLE,
  CONSTRAINT `fk_gearSkater_1`
    FOREIGN KEY (`gearID`)
    REFERENCES `gearBoss`.`gear` (`gearID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gearSkater_2`
    FOREIGN KEY (`skaterID`)
    REFERENCES `gearBoss`.`skater` (`skaterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`session` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`session` (
  `sessionID` INT NOT NULL AUTO_INCREMENT,
  `sessionDate` DATETIME NULL,
  `sessionDescription` VARCHAR(45) NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`sessionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gearBoss`.`skaterSession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`skaterSession` ;

CREATE TABLE IF NOT EXISTS `gearBoss`.`skaterSession` (
  `skaterSessionID` INT NOT NULL AUTO_INCREMENT,
  `skaterID` INT NULL,
  `sessionID` INT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` INT NULL,
  `updatedBy` INT NULL,
  PRIMARY KEY (`skaterSessionID`),
  INDEX `fk_skaterSession_1_idx` (`skaterID` ASC) VISIBLE,
  INDEX `fk_skaterSession_2_idx` (`sessionID` ASC) VISIBLE,
  CONSTRAINT `fk_skaterSession_1`
    FOREIGN KEY (`skaterID`)
    REFERENCES `gearBoss`.`skater` (`skaterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skaterSession_2`
    FOREIGN KEY (`sessionID`)
    REFERENCES `gearBoss`.`session` (`sessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `gearBoss` ;

-- -----------------------------------------------------
-- Placeholder table for view `gearBoss`.`skaterGear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gearBoss`.`skaterGear` (`skaterID` INT, `firstName` INT, `lastName` INT, `gearID` INT, `gearName` INT, `size` INT, `gearLabel` INT);

-- -----------------------------------------------------
-- Placeholder table for view `gearBoss`.`statusOfGear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gearBoss`.`statusOfGear` (`gearID` INT, `gearName` INT, `gearLabel` INT, `gearTypeDescription` INT, `gearStatusDescription` INT, `conditionDescription` INT, `description` INT);

-- -----------------------------------------------------
-- procedure updateSkater
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`updateSkater`;

DELIMITER $$
USE `gearBoss`$$
create procedure updateSkater 
  (skaterID int,
  updateField varchar(45),
  updateValue varchar(45))
sql security invoker
begin

  declare loggedUser varchar(45);
  declare loggedUserID int;  
  set @loggedUser = (select substring_index(current_user(), "@", 1));
  set @loggedUserID = (select userID from user where username = @loggedUser);

  set @updt = concat("update skater set ", updateField, " = '", updateValue, "', updateDate = CURRENT_TIMESTAMP, updatedBy = ", cast(@loggedUserID as char), " where skaterID = ", cast(skaterID as char));
  prepare stmt from @updt;
  execute stmt;

  deallocate prepare stmt;
 
end;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertSkater
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`insertSkater`;

DELIMITER $$
USE `gearBoss`$$
CREATE PROCEDURE insertSkater 
(firstName varchar(45),
lastName varchar(45),
phone varchar(45),
email varchar(45),
contacted bool,
position varchar(45),
referredBy int)
sql security invoker
BEGIN

	declare loggedUser varchar(45);
    declare loggedUserID int;
    set @loggedUser = (select substring_index(current_user(), "@", 1));
	set @loggedUserID = (select userID from user where username = @loggedUser);
    
	set @updt = concat("insert into skater (firstName, lastName, phone, email, contacted, position, referredBy, createDate, updateDate, createdBy, updatedBy) values ('", firstName, "', '", lastName, "', '", phone, "', '", email, "', ", contacted, ", '", position, "', ", cast(@referredBy as char), ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ", @loggedUserID, ", ", @loggedUserID, ")");
	prepare stmt from @updt;
	execute stmt;

	deallocate prepare stmt;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertGear
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`insertGear`;

DELIMITER $$
USE `gearBoss`$$
CREATE PROCEDURE insertGear 
  (gearName varchar(45),
  gearTypeID int,
  gearConditionID int,
  gearStatusID int,
  gearLabel varchar(45),
  gearSize varchar(45))
  sql security invoker
BEGIN

  declare loggedUser varchar(45);
  declare loggedUserID int;
  set @loggedUser = (select substring_index(current_user(), "@", 1));
  set @loggedUserID = (select userID from user where username = @loggedUser);

  set @updt = concat("insert into gear (gearName, gearTypeID, gearConditionID, gearStatusID, gearLabel, size, createDate, updateDate, createdBy, updatedBy) values ('", gearName, "', ", gearTypeID, ", ", gearConditionID, ", ", gearStatusID, ", '", gearLabel, "', '", gearSize, "', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ", @loggedUserID, ", ", @loggedUserID, ")");
  prepare stmt from @updt;
  execute stmt;

  deallocate prepare stmt;
  
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateGear
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`updateGear`;

DELIMITER $$
USE `gearBoss`$$
create procedure updateGear 
  (gearID int,
  updateField varchar(45),
  updateValue varchar(45))
sql security invoker
begin

  declare loggedUser varchar(45);
  declare loggedUserID int;  
  set @loggedUser = (select substring_index(current_user(), "@", 1));
  set @loggedUserID = (select userID from user where username = @loggedUser);

  set @updt = concat("update gear set ", updateField, " = '", updateValue, "', updateDate = CURRENT_TIMESTAMP, updatedBy = ", cast(@loggedUserID as char), " where gearID = ", gearID);
  prepare stmt from @updt;
  execute stmt;

  deallocate prepare stmt;
 
end;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertSession
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`insertSession`;

DELIMITER $$
USE `gearBoss`$$
CREATE PROCEDURE insertSession
(sessionDate datetime,
  sessionDescription varchar(45))
sql security invoker
BEGIN

	declare loggedUser varchar(45);
    declare loggedUserID int;
    set @loggedUser = (select substring_index(current_user(), "@", 1));
	set @loggedUserID = (select userID from user where username = @loggedUser);
    
	set @updt = concat("insert into session (sessionDate, sessionDescription, createDate, updateDate, createdBy, updatedBy) values (", sessionDate, ", '", sessionDescription, ", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ", @loggedUserID, ", ", @loggedUserID, ")");
	prepare stmt from @updt;
	execute stmt;

	deallocate prepare stmt;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure updateSession
-- -----------------------------------------------------

USE `gearBoss`;
DROP procedure IF EXISTS `gearBoss`.`updateSession`;

DELIMITER $$
USE `gearBoss`$$
create procedure updateSession
  (sessionID int,
  updateField varchar(45),
  updateValue varchar(45))
sql security invoker
begin

  declare loggedUser varchar(45);
  declare loggedUserID int;  
  set @loggedUser = (select substring_index(current_user(), "@", 1));
  set @loggedUserID = (select userID from user where username = @loggedUser);

  set @updt = concat("update session set ", updateField, " = '", updateValue, "', updateDate = CURRENT_TIMESTAMP, updatedBy = ", cast(@loggedUserID as char), " where sessionID = ", sessionID);
  prepare stmt from @updt;
  execute stmt;

  deallocate prepare stmt;
 
end;$$

DELIMITER ;

-- -----------------------------------------------------
-- View `gearBoss`.`skaterGear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`skaterGear`;
DROP VIEW IF EXISTS `gearBoss`.`skaterGear` ;
USE `gearBoss`;
CREATE  OR REPLACE VIEW skaterGear AS
select s.skaterID, s.firstName, 
s.lastName,
g.gearID,
g.gearName,
g.size,
g.gearLabel
from skater s
left join gearSkater gs on s.skaterID = gs.skaterID
left join gear g on g.gearID = gs.gearID;

-- -----------------------------------------------------
-- View `gearBoss`.`statusOfGear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gearBoss`.`statusOfGear`;
DROP VIEW IF EXISTS `gearBoss`.`statusOfGear` ;
USE `gearBoss`;
CREATE  OR REPLACE VIEW statusOfGear AS
select g.gearID, g.gearName, g.gearLabel, gt.gearTypeDescription, gs.gearStatusDescription, gc.conditionDescription, d.description
from gear g
left join gearStatus gs on gs.gearStatusID = g.gearStatusID
left join gearType gt on gt.gearTypeID = g.gearTypeID
left join gearCondition gc on gc.gearConditionID = g.gearConditionID
left join description d on d.gearID = g.gearID;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
